name: Second workflow
on: 
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps: 
         - name: check out branch
           run: actions/checkout@v5
           
         - name: Display the content of the file
           run: cat eshan.txt

         - name: Display date
           run: date

         - name: Display list
           run: ls -lrth
