name: Hello World - Every 5 Minute

on:
  #schedule:
    workflow_dispatch:        # Optional: Allows manual trigger

  #  - cron: "*/5 * * * *"  # Runs every 1 minute

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello World! $(date)"
