name: Docker Matrix
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,linux]
        images: [hello-world, alpine, ariefmd/maven-web:1.0.0, ariefmd/maven-web-app:1.0.1]
    steps:
      - name: Docker details
        run: docker info
      - name: Run image
        run: docker run ${{ matrix.images }}
