name: Docker Matrix
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        images: [hello-world, alpine, mongo, ariefmd/maven-web-application:8.0.9]
    steps:
      - name: Docker details
        run: docker info
      - name: Run image
        run: docker run ${{ matrix.images }}
