name: Docker Matrix
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux]
        images: [ariefmd/maven-web:1.0.0]
    steps:
      - name: Docker details
        run: docker info
      - name: Run image
        run: docker run ${{ matrix.images }}
