name: Job-Timeout-Example
on:
   workflow_dispatch

jobs:
   sample:
      runs-on: ubuntu-latest
      timeout-minutes: 1
      steps:
         - name: Start
           run: echo "Welcome to Timeout"
         - name: Started the Timeout 
           # timeout-minutes: 1
           run: sleep 150
         - run: echo "Timeout completed"
