name: Pipeline workflow

on:
  workflow_dispatch:  # allows manual run from Actions tab

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Display the file content
        run: |
          echo "Eshan Shaik" > eshan.txt
          ls -lrth
          cat eshan.txt
          uname
          whoami
          date
          uptime
          pwd
