name: Sheel script workflows

on:
   workflow_dispatch:
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4
           
         - name: User name
           run: echo "Arief"
         - name: File Permissions
           run: chmod +x run-script.sh
         - name: Run the shell script
           run: ./run-script.sh

      
           
           
