name: Step level Env Example
on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    env:
       CITY: HYD
       NAME: ARIEF
    steps:
      - name: Step level example
        run: |
          echo "Arief Mohammad" > arief.txt
          echo "My city is $CITY"
          echo "$NAME staying at $CITY"
          ls -lrth
          cat arief.txt

      - name: Next step (env will NOT work here)
        run: |
          echo "City is $CITY and trainer is $NAME"
