name: Testing Workflow

on:
  workflow_dispatch:   # Enables manual run from GitHub Actions tab

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Required for most workflows

      - name: Hello display
        run: echo "Arief Mohammad"

      - name: Display the Date
        run: date
