name: Second workflow
on: push
jobs:
   build:
      runs-on: ubuntu-latest
      steps: 
         - name: Welcome message
           run: echo "Hello eshan babu" > eshan.txt

         - name: Display date
           run: date

         - name: Display list
           run: ls -lrth

         - name: server name
           run: uname

         - name: Print current user
           run: whoami
