name: Artifact Upload and Download the Example
on: 
   workflow_dispatch:
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
         - name: Create File
           run: echo "Hello this is Arief Mohammad" > arief.txt

         - name: Upload file as Artifact
           uses: actions/upload-artifact@v4
           with: 
              name: datafile
              path: arief.txt
   job2:
      runs-on: ubuntu-latest
      steps:
         - name: Download the Artifact
           uses: actions/download-artifact@v4
           with: 
              name: datafile

         - name: Display the file Data
           run: cat arief.txt
          

